<?php
	define("GALLERYDIR", FOLDERFILES."/gallery");
	define("GALLERYNOPREVIEW", FOLDERCOMMON."/images/reiz/nopreview.jpg"); // must be jpg
	define("GALLERYTHUMBNAILWIDTH", 100);
	define("GALLERYTHUMBNAILHEIGHT", 75);
	define("GALLERYUSELIGHTBOX", false);
	define("GALLERYDEFAULTTITLE", "Gallery");
	define("GALLERYDEFAULTTEXT", "&nbsp;");
	define("GALLERYPREVLINKTEXT", "Back to previous folder"); // ".."
?>