<?php
	define("GALLERYLINKPATH", "gallery");
	define("GALLERYLOCALPATH", "content/gallery");
	define("GALLERYTHUMBSPATH", "content/gallery-thumbs");
	define("GALLERYNOPREVIEW", "common/images/reiz/nopreview.jpg"); // must be jpg
	define("GALLERYTHUMBNAILWIDTH", 100);
	define("GALLERYTHUMBNAILHEIGHT", 75);
	define("GALLERYUSELIGHTBOX", false);
	define("GALLERYDEFAULTTITLE", "Gallery");
	define("GALLERYDEFAULTTEXT", "&nbsp;");
	define("GALLERYPREVLINKTEXT", "Back to previous folder");
?>