<?php
//------------------------------------------------------------
// Project:		reiZ CMS
// License:		GPL v2
//
// Contents:		Query definition for a mySQL database
// Created by:		Philip Jensen (me@iensenfirippu.dk)
// Class version:	0.1
// Date:				2015/08/10
//
// TODO: Currently not implemented, Replace with prepared statements
//------------------------------------------------------------

include_once(FOLDERCLASSES.'/dbvendor/mysql/query.inc');
?>