<?php
/* ################ reiZ CMS #####################
############### User Config file #################
Used to set your personal configuration.
Any value that isn't set here will automatically
use the value set in the default config file.
############################################### */

//define("DEBUG",				false);
//define("DISPLAYERRORS",		false);
//define("CLEANURL",			true);
  define("ONELINEOUTPUT",		false);
  
  define("URLROOT",				"http://marugawalite");
//define("INDEXPAGE",			"home");
//define("LOGINPAGE",			"inlog");
//define("ADMINPAGE",			"nimba");
  define("TIMEZONE",			"Europe/Copenhagen");

//define("DEFAULTTHEME",		"default");
//define("DEFAULTMASTER",		"default");
//define("DEFAULTMASTERID",		1);
//define("DEFAULTPAGE",			"default");

//define("ITEMSPERPAGE",		25);

//define("DBVENDOR",			"mysql");
  define("DBPREFIX",			EMPTYSTRING);
  define("DBSERVER",			"localhost");
  define("DBDATABASE",			"iensenfirippu");
  define("DBUSERNAME",			"root");
  define("DBPASSWORD",			"root1234");
  define("DBENCODING",			"utf8");

  define("MAINTENANCEMODE",		true);
  define("MAINTENANCEIP",		"127.0.0.1");
?>
