<!doctype html>
<html>
	<head>
		<title>Installing reiZ CMS</title>
		<meta charset="UTF-8" />
		<link rel="icon" type="image/png" href="../common/images/favicon.png" />
		<link rel="stylesheet" type="text/css" href="install.css" />
	</head>
	<body>
		<div id="wrapper">
			<div id="main">
				<div id="stepnumber"><?php echo $stepnumber; ?></div>
				<div id="top">
					<h1><?php echo $title; ?></h1>
				</div>
				<div id="content">
